"""DrawAI v2 package contracts."""

from .fusion import FusionConfig, FusionResult, fuse_candidates
from .packages import (
    RunClassification,
    classify_run_root,
    element_dir,
    read_run_package,
    write_asset_package,
    write_element_plan,
    write_run_package,
)
from .parsers import ocr_payload_to_candidates, sam3_payload_to_candidates
from .registry import DrawAiRegistry, default_registry
from .refine import (
    CODEX_ELEMENT_ANALYSIS_SCHEMA,
    REFINED_ELEMENT_PLANS_EXPORT_SCHEMA,
    CodexElementRefiner,
    RefineConfig,
    RefinementValidationError,
    codex_analysis_to_v2_element_plans,
    codex_analysis_to_v2_removal_records,
    validate_refined_elements,
)
from .schema import (
    ASSET_PACKAGE_SCHEMA,
    ELEMENT_CANDIDATE_SCHEMA,
    ELEMENT_PLAN_SCHEMA,
    RUN_PACKAGE_SCHEMA,
    AssetPackage,
    AssetStatus,
    ElementCandidate,
    ElementPlan,
    ProcessingIntent,
    ReviewStatus,
    RunPackage,
    utc_now,
    validate_bbox,
    validate_asset_package,
    validate_element_candidate,
    validate_element_plan,
    validate_run_package,
    validate_run_package_payload,
)

__all__ = [
    "ASSET_PACKAGE_SCHEMA",
    "ELEMENT_CANDIDATE_SCHEMA",
    "ELEMENT_PLAN_SCHEMA",
    "FusionConfig",
    "FusionResult",
    "RUN_PACKAGE_SCHEMA",
    "AssetPackage",
    "AssetStatus",
    "CODEX_ELEMENT_ANALYSIS_SCHEMA",
    "CodexElementRefiner",
    "DrawAiRegistry",
    "ElementCandidate",
    "ElementPlan",
    "ProcessingIntent",
    "REFINED_ELEMENT_PLANS_EXPORT_SCHEMA",
    "RefineConfig",
    "RefinementValidationError",
    "ReviewStatus",
    "RunClassification",
    "RunPackage",
    "classify_run_root",
    "default_registry",
    "element_dir",
    "fuse_candidates",
    "ocr_payload_to_candidates",
    "read_run_package",
    "sam3_payload_to_candidates",
    "utc_now",
    "validate_asset_package",
    "validate_bbox",
    "validate_element_candidate",
    "validate_element_plan",
    "validate_refined_elements",
    "validate_run_package",
    "validate_run_package_payload",
    "write_asset_package",
    "write_element_plan",
    "write_run_package",
    "codex_analysis_to_v2_element_plans",
    "codex_analysis_to_v2_removal_records",
]
